language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ghurt' ]; then cd .. && eval "mv $currentfolder generator-ghurt" && cd generator-ghurt; fi

